/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Affix: typeof import('./src/components/common/affix/Affix.vue')['default']
    BlockTableContent: typeof import('./src/components/layout/CustomDataEntity/DataContentType/BlockTableContent.vue')['default']
    BlockTreeContent: typeof import('./src/components/layout/CustomDataEntity/DataContentType/BlockTreeContent.vue')['default']
    copy: typeof import('./src/components/layout/InfoDataEntity/InfoDataEntity copy.vue')['default']
    CustomDataCreateEntity: typeof import('./src/components/layout/CustomDataEntity/CustomDataCreateEntity.vue')['default']
    CustomDataEntity: typeof import('./src/components/layout/CustomDataEntity/CustomDataEntity.vue')['default']
    'CustomDataEntity.type': typeof import('./src/components/layout/CustomDataEntity/CustomDataEntity.type.vue')['default']
    CustomDataTable: typeof import('./src/components/layout/CustomDataTable/CustomDataTable.vue')['default']
    'CustomDataTable.type': typeof import('./src/components/layout/CustomDataTable/CustomDataTable.type.vue')['default']
    FieldEditable: typeof import('./src/components/layout/InfoDataEntity/FieldEditable.vue')['default']
    FieldRenderer: typeof import('./src/components/layout/InfoDataEntity/FieldRenderer.vue')['default']
    InfoDataCreateEntity: typeof import('./src/components/layout/InfoDataEntity/InfoDataCreateEntity.vue')['default']
    InfoDataEntity: typeof import('./src/components/layout/InfoDataEntity/InfoDataEntity.vue')['default']
    InfoDataTable: typeof import('./src/components/layout/InfoDataTable/InfoDataTable.vue')['default']
    InfoEditableField: typeof import('./src/components/common/infodata/InfoEditableField/InfoEditableField.vue')['default']
    InfoEditField: typeof import('./src/components/common/infodata/infoEditField/InfoEditField.vue')['default']
    InfoField: typeof import('./src/components/common/infodata/infoField/InfoField.vue')['default']
    InfoTable: typeof import('./src/components/layout/ProjectDataTable/InfoTable.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    Panel: typeof import('./src/components/common/dashboard/panel/Panel.vue')['default']
    PanelFull: typeof import('./src/components/dashboard/panel/PanelFull.vue')['default']
    PanelItem: typeof import('./src/components/common/dashboard/panel/PanelItem.vue')['default']
    PanelMini: typeof import('./src/components/dashboard/panel/PanelMini.vue')['default']
    ProjectDataTable: typeof import('./src/components/layout/CustomDataTable/ProjectDataTable.vue')['default']
    ProjectModal: typeof import('./src/components/ui/projectModal/projectModal.vue')['default']
    ProjectModel: typeof import('./src/components/ui/projectModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveAffix: typeof import('./src/components/common/affix/SaveAffix.vue')['default']
  }
}
