/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomDataTable: typeof import('./src/components/layout/CustomDataTable/CustomDataTable.vue')['default']
    InfoDataTable: typeof import('./src/components/layout/InfoDataTable/InfoDataTable.vue')['default']
    InfoTable: typeof import('./src/components/layout/ProjectDataTable/InfoTable.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpin: typeof import('naive-ui')['NSpin']
    Panel: typeof import('./src/components/common/dashboard/panel/Panel.vue')['default']
    PanelFull: typeof import('./src/components/dashboard/panel/PanelFull.vue')['default']
    PanelItem: typeof import('./src/components/common/dashboard/panel/PanelItem.vue')['default']
    PanelMini: typeof import('./src/components/dashboard/panel/PanelMini.vue')['default']
    ProjectDataTable: typeof import('./src/components/layout/CustomDataTable/ProjectDataTable.vue')['default']
    ProjectModal: typeof import('./src/components/ui/projectModal/projectModal.vue')['default']
    ProjectModel: typeof import('./src/components/ui/projectModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
